require:
  - rubocop-codeur
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'test/dummy/db/schema.rb'
    - 'test/dummy/tmp/**/*'
  TargetRubyVersion: 2.7
  TargetRailsVersion: 7
  NewCops: enable

Rails:
  Enabled: true

Codeur/RailsAppPatterns:
  Enabled: true
  ForbiddenPatterns:
    - presenters
    - view_objects
    - modules

Codeur/RailsAvoidInstanceMethodsInHelpers:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent
  IndentationWidth: 2

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/ClassStructure:
  Enabled: true
  AutoCorrect: false
  ExpectedOrder:
    - devise
    - module_inclusion
    - constants
    - attributes
    - has_ancestry
    - delegated_type
    - belongs_to
    - has_many
    - has_one
    - attachments
    - public_delegate
    - class_macros
    - callbacks
    - state_machine
    - aasm
    - scope
    - default_scope
    - validations
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    attachments:
      - has_one_attached
      - has_many_attached
      - has_attached_file
    attributes:
      - attr_accessor
      - attr_reader
      - attr_writer
      - attr_readonly
      - emojify
      - enum
      - monetize
      - serialize
      - has_secure_token
      - alias_attribute
      - slug
    class_macros:
      - acts_as_voter
      - pg_search_scope
      - counter_culture
      - accepts_nested_attributes_for
      - paginates_per
      - ransack_alias
      - ransacker
      - ratyrate_rater
    callbacks:
      - before_validation
      - after_validation
      - before_save
      - around_save
      - before_create
      - around_create
      - before_update
      - around_update
      - before_destroy
      - around_destroy
      - after_destroy
      - after_create
      - after_save
      - after_commit
      - after_rollback
    validations:
      - validates_associated
      - validates
      - validate

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Enabled: true
  Max: 200
  AutoCorrect: false
  Exclude:
    - 'db/migrate/*'

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Lint/DuplicateMethods:
  Enabled: true
  Exclude:
    - 'db/migrate/*'

Lint/MissingSuper:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 65
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Enabled: true
  Max: 60
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - 'app/states/*'

Metrics/ClassLength:
  Enabled: true
  Max: 300
  Exclude:
    - 'app/models/**/*'

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Metrics/MethodLength:
  Enabled: true
  Max: 60
  Exclude:
    - 'db/migrate/*'

Metrics/ModuleLength:
  Enabled: true
  Max: 300

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10

Minitest/TestMethodName:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: true
  Max: 30

# Disabled because it doesn't with symbols like: record_001
Naming/VariableNumber:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: true
  Exclude:
    - 'db/migrate/{2012,2013,2014,2015,2016,2017,2018}*.rb'

Rails/EnvironmentVariableAccess:
  Enabled: true
  AllowReads: true

Rails/FilePath:
  Enabled: true
  EnforcedStyle: arguments

Rails/ReversibleMigration:
  Enabled: true
  Exclude:
    - 'db/migrate/{2012,2013,2014,2015,2016,2017,2018}*.rb'

Rails/MigrationClassName:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
  Exclude:
    - 'lib/tasks/**/*'
    - 'db/migrate/*.rb'

Rails/TimeZone:
  Enabled: true
  AutoCorrect: false

Rails/UnknownEnv:
  Enabled: true
  Environments:
    - development
    - test
    - staging
    - production

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  AutoCorrect: true

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: true
  MinBodyLength: 3

Style/HashEachMethods:
  Enabled: true
  AutoCorrect: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/HashTransformKeys:
  Enabled: true
  AutoCorrect: true

Style/HashTransformValues:
  Enabled: true
  AutoCorrect: true

Style/IfUnlessModifier:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: true
  MinSize: 7

Style/FormatStringToken:
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'config/routes/*'
